title: Jiayi Zhou
email: jiayi22@stu.pku.edu.cn

google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=zh-CN&user=T6OlzVsAAAAJ
cv_link: /assets/files/curriculum_vitae.pdf
github_link: https://github.com/jiayizhou22
avatar: /assets/img/avatar.jpg
enable_footnote: false
auto_dark_mode: false
font: "Serif"

url: "https://jiayizhou22.github.io"
baseurl: ""

collections:
  pages:
    output: true
    permalink: /:name/

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: jiayi zhou, neural operators, PDEs, PKU
description: Jiayi Zhou is a Fourth-year undergraduate at Peking University, focusing on scientific machine learning and neural operators for partial differential equations.
canonical: https://jiayizhou22.github.io/

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
